VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cpuDateInterval"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
' This class combines employee and wg/line date interval

' Get rid of cpuLineDateInterval after this works


Public EmployeeNumber As Long
Public WorkgroupNumber As Long
Public LineNumber As Long
Public StartDate As Date
Public EndDate As Date

